name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Script on PR
      if: github.event_name == 'pull_request'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Running tests on pull request..."
          # Place test commands here
          # For example, if you're using PHPUnit:
          # ./vendor/bin/phpunit

          # cd "<your-project-directory>"
          php artisan test
          echo "All tests are working..."

    - name: Deploy to Server
      if: github.event_name == 'push'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "BEGINNING CI/CD SCRIPT"
          # cd "<your-project-directory>"
          git pull origin main
          php composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan optimize:clear
          php artisan migrate --seed
          php artisan clear-compiled
          php artisan storage:link
          echo -e "UPDATE COMPLETED SUCESSFULLY"
